/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JOptionPane;
import socket_ciente.Cliente;

/**
 *
 * @author neommunications
 */
public class JP_02 extends javax.swing.JPanel {

    Main Main;
    String nombre_servicio;
    String nombre_metodo;
    String server;
    boolean swcontrol = false;

    private final String[] lstMetodos;
    private final ArrayList<JP_03> lst_JP_03 = new ArrayList<>();
    public JP_02(Main Main, String a) {
        this.nombre_servicio = a;
        this.Main = Main;
        this.lstMetodos = Main.getIntegracion().getStringMetodos().split(",");
        
        this.server = Main.getIntegracion().getIPP();
        initComponents();
        jLabel_server.setText(this.server);
        this.jTextArea_WSDL.setText(Main.getIntegracion().get_XML_WSDL());
        this.setSize(900, 600);
        
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea_WSDL = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_Request = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_Response = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_server = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea_resultadoPantalla = new javax.swing.JTextArea();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(lstMetodos));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccionar Metodo");

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane1.setViewportView(jPanel1);

        jButton2.setText("Generar soap");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText(nombre_servicio);

        jTextArea_WSDL.setColumns(20);
        jTextArea_WSDL.setRows(5);
        jScrollPane5.setViewportView(jTextArea_WSDL);

        jTabbedPane1.addTab("WSDL", jScrollPane5);

        jTextArea_Request.setColumns(20);
        jTextArea_Request.setRows(5);
        jTextArea_Request.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextArea_RequestKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea_Request);

        jTabbedPane1.addTab("SOAP Request", jScrollPane2);

        jTextArea_Response.setColumns(20);
        jTextArea_Response.setRows(5);
        jScrollPane3.setViewportView(jTextArea_Response);

        jTabbedPane1.addTab("SOAP Response", jScrollPane3);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Servidor: ");

        jLabel_server.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_server.setText("jLabel4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel_server, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel_server))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jButton3.setText("Enviar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextArea_resultadoPantalla.setColumns(20);
        jTextArea_resultadoPantalla.setRows(5);
        jScrollPane4.setViewportView(jTextArea_resultadoPantalla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel2)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(95, 95, 95)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Main.pintarPanelInicio();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        //default title and icon
        //JOptionPane.showMessageDialog(Main, jComboBox1.getSelectedItem());
        nombre_metodo = (String) jComboBox1.getSelectedItem();
        setInput(nombre_metodo);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String datos = "";
        
        boolean ba = true;
        for(JP_03 a: lst_JP_03){
            if(ba){datos += a.jLabel1.getText(); ba = false;}else
            datos += ","+a.jLabel1.getText();
            datos += " : "+a.jTextField1.getText();
        }
        
        String SOAP = Main.getIntegracion().getSOAP_Request(nombre_metodo, datos);
        //JOptionPane.showMessageDialog(null, datos);
        jTextArea_Request.setText(SOAP);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Enviar SOAP al server
        String ip = server.split(":")[0];
        int puerto =  Integer.parseInt(server.split(":")[1]);
        String msg = jTextArea_Request.getText();
        String SOAP_RESPONSE;
        String ssss ;
        
        //msg = msg.replaceAll("\n", " "); //Quitar saltos de linea
        String ss = Main.getIntegracion().get_Lenguaje_del_servidor();
        
        
        if( ss != null && (ss.equals("c") || ss.equals("C"))){
            SOAP_RESPONSE = new Cliente(ip, puerto, msg, "c").get();
           
        }else{
            SOAP_RESPONSE = new Cliente(ip, puerto, msg, "j").get();
        }
        
        if(SOAP_RESPONSE != null){
            jTextArea_Response.setText(Main.getIntegracion().get_XML_Response(SOAP_RESPONSE));
            ssss = Main.getIntegracion().get_resultado_response();
        
        }else{
            ssss = "Error al conectarce al servidor";
        }
        
        jTextArea_resultadoPantalla.setText(ssss);
        
    }//GEN-LAST:event_jButton3ActionPerformed
    public void Respuesta_del_server(String respuesta){
        
        this.jTextArea_Response.setText(Main.getIntegracion().get_XML_Response(respuesta));
        
    }
    private void jTextArea_RequestKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea_RequestKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_CONTROL || 157 == evt.getKeyCode()) {
            swcontrol = true;
        } else if (swcontrol && evt.getKeyCode() == KeyEvent.VK_A) {
            jTextArea_Request.selectAll();
            swcontrol = false;
        }else if (swcontrol && evt.getKeyCode() == KeyEvent.VK_C) {
            jTextArea_Request.copy();
            swcontrol = false;
        }else if (swcontrol && evt.getKeyCode() == KeyEvent.VK_V) {
            jTextArea_Request.paste();
            swcontrol = false;
        }
    }//GEN-LAST:event_jTextArea_RequestKeyPressed

    public void setInput(String metodoSelected) {
       // /*
       int index = 0;
        jPanel1.removeAll();
        jPanel1.updateUI();
        
        ArrayList<String> lst_Tests = Main.getIntegracion().getParametros(metodoSelected);
        
        if(lst_Tests !=null){
        
        
            lst_JP_03.clear();
            for (String test : lst_Tests) {
                JP_03 input = new JP_03(test);
                lst_JP_03.add(input);
                jPanel1.add(input);
                index +=1;
            }
        }else{
            jTextArea_resultadoPantalla.setText("Error al buscar el portype input e output");
        }
//*/
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_server;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea_Request;
    public javax.swing.JTextArea jTextArea_Response;
    private javax.swing.JTextArea jTextArea_WSDL;
    private javax.swing.JTextArea jTextArea_resultadoPantalla;
    // End of variables declaration//GEN-END:variables
}
