<definitions xmlns:xsd="xsd" xmlns:soap="soap" name="Banco">
<types>
<xsd:schema></xsd:schema>
</types>
<message name="Request_Banco">
<part name="ID" type="xsd:double"/>
</message>
<message name="No_requiere_parametros">
<part name="No_requiere_parametros" type="xsd:string"/>
</message>
<message name="Response_Banco">
<part name="Value" type="xsd:string"/>
</message>
<message name="Fault">
<part name="errorconpeticion" type="xsd:string"/>
</message>
<portType name="glossaryTerms">
<operation name="getAll_Banco">
<input message="No_requiere_parametros"/>
<output message="Response_Banco"/>
<fault message="Fault"/>
</operation>
<operation name="getPersona_Banco">
<input message="Request_Banco"/>
<output message="Response_Banco"/>
<fault message="Fault"/>
</operation>
</portType>
<binding languaje="java">
<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
<operation name="getAll_Banco">
<input>
<soap:body use="literal"/>
</input>
<output>
<soap:body use="literal"/>
</output>
<fault>
<soap:fault use="literal"/>
</fault>
</operation>
<operation name="getPersona_Banco">
<input>
<soap:body use="literal"/>
</input>
<output>
<soap:body use="literal"/>
</output>
<fault>
<soap:fault use="literal"/>
</fault>
</operation>
</binding>
<service name="CalculatorWSService">
<port name="10575">
<soap:address location="172.16.4.52"/>
</port>
</service>
</definitions>